<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
 <OutputType>WinExe</OutputType>
 <TargetFramework>net8.0-windows</TargetFramework>
 <Nullable>enable</Nullable>
 <ImplicitUsings>enable</ImplicitUsings>
 <UseWPF>true</UseWPF>
 </PropertyGroup>

 <ItemGroup>
   <PackageReference Include="ClosedXML" Version="0.105.0" />
 </ItemGroup>

 <ItemGroup>
   <ProjectReference Include="..\HEMA.Common\HEMA.Common.csproj" />
 </ItemGroup>

 <ItemGroup>
   <Compile Update="RaitingWindow.xaml.cs">
     <SubType>Code</SubType>
   </Compile>
 </ItemGroup>

 <ItemGroup>
   <None Update="raw\beep.mp3">
     <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
   </None>
   <None Update="raw\longBeep.mp3">
     <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
   </None>
   <None Update="raw\tick.mp3">
     <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
   </None>
 </ItemGroup>

</Project>
